export default {
  GET_EDITOR_IFRAME_KEY: 'GET_EDITOR_IFRAME_KEY',
  IFRAME_LOADED: 'IFRAME_LOADED',
  PROGRAM_LOADED: 'PROGRAM_LOADED',
  REMOVE_EDITOR_IFRAME_KEY: 'REMOVE_EDITOR_IFRAME_KEY',
  SET_EDITOR_IFRAME_KEY: 'SET_EDITOR_IFRAME_KEY',
  SHOW_TOAST: 'SHOW_TOAST',
  WAIT_PROGRAM_TO_TEST: 'WAIT_PROGRAM_TO_TEST',
};
